services:
  setup:
    image: "python:3.12-slim"
    volumes:
      - .:/app
    working_dir: /app
    command: python scripts/dev/generate_tokens.py
    env_file:
      - .env

  nginx:
    build:
      context: ./scripts/dev
      dockerfile: nginx.Dockerfile
    ports:
      - "127.0.0.1:3600:80"
    environment:
      NGINX_ENVSUBST_OUTPUT_DIR: /etc/nginx
    env_file:
      - .env
    depends_on:
      setup:
        condition: service_completed_successfully
